export const SET_DRAWER_OPEN = "SET_DRAWER_OPEN";
export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const SET_DRAWER_CLOSED = "SET_DRAWER_CLOSED";
export const SET_CONTACT_MODAL_OPEN = "SET_CONTACT_MODAL_OPEN";
export const SET_CONTACT_MODAL_CLOSED = "SET_CONTACT_MODAL_CLOSED";
export const UPDATE_NAV_HEIGHT = "UPDATE_NAV_HEIGHT";
